name: PowerShell CI

on: [push, pull_request]

jobs:
  pester-test:
    name: Run Pester Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Pester
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
        shell: pwsh

      - name: Run Pester tests
        run: |
          . ./src/Get-Greeting.ps1
          Invoke-Pester -Script tests/Get-Greeting.Tests.ps1 -Passthru
        shell: pwsh
